# SwiftLint Configuration for Gr4vy Swift SDK
# https://github.com/realm/SwiftLint

# Paths to include during linting
included:
  - gr4vy-swift
  - gr4vy-swiftTests

# Paths to exclude during linting
excluded:
  - gr4vy-swift.xcodeproj
  - gr4vy-swift.xcworkspace
  - Pods
  - Carthage
  - .build
  - .swiftpm
  - DerivedData
  - .git
  - Package.swift

# Rules to disable
disabled_rules:
  - trailing_whitespace # Can be auto-fixed
  - todo # TODOs are acceptable in development

# Rules to enable (opt-in rules)
opt_in_rules:
  - accessibility_label_for_image
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 10

cyclomatic_complexity:
  warning: 10
  error: 20

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 2
  max_length: 50
  excluded:
    - T
    - U
    - V

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - to
    - at
    - in
    - on
    - of
    - or
    - is
    - it
    - up
    - x
    - y
    - z

nesting:
  type_level: 2
  function_level: 5

large_tuple:
  warning: 3
  error: 5

# Security-focused rules
force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: warning

# Code quality rules
empty_enum_arguments:
  severity: warning

empty_parameters:
  severity: warning

empty_parentheses_with_trailing_closure:
  severity: warning

explicit_init:
  severity: warning

fatal_error_message:
  severity: error

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  gr4vy-swift
                    \/\/
                    \/\/  Created by Gr4vy
                    \/\/

# Performance rules
contains_over_filter_count:
  severity: warning

contains_over_filter_is_empty:
  severity: warning

contains_over_first_not_nil:
  severity: warning

first_where:
  severity: warning

last_where:
  severity: warning

# API Design rules
function_default_parameter_at_end:
  severity: warning

lower_acl_than_parent:
  severity: warning

# Testing rules
single_test_class:
  severity: warning

quick_discouraged_call:
  severity: warning

quick_discouraged_focused_test:
  severity: error

quick_discouraged_pending_test:
  severity: warning

# Documentation rules
missing_docs:
  warning:
    - public
    - open
  error:
    - public
    - open
  excludes_extensions: true
  excludes_inherited_types: true

# Multiline rules
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  first_parameter_location: next_line

# Import organization
sorted_imports:
  severity: warning

# Trailing comma rules
trailing_comma:
  mandatory_comma: true

# Closure rules
closure_end_indentation:
  severity: warning

closure_spacing:
  severity: warning

# Pattern matching
pattern_matching_keywords:
  severity: warning

# Operator usage
operator_usage_whitespace:
  severity: warning

# Naming conventions
generic_type_name:
  min_length: 1
  max_length: 20

# Custom rules for SDK-specific patterns
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '(?<!\/\/.*)\bprint\s*\('
    message: "Use Gr4vyLogger instead of print statements"
    severity: warning

  no_hardcoded_strings:
    name: "No Hardcoded URLs"
    regex: '(?<!\/\/.*)"https?:\/\/'
    message: "Use URL construction utilities instead of hardcoded URLs"
    severity: warning

  proper_error_handling:
    name: "Proper Error Handling"
    regex: 'try!\s+'
    message: "Use proper error handling instead of try!"
    severity: error

  api_documentation:
    name: "API Documentation Required"
    regex: '^public\s+(class|struct|enum|protocol|func|var|let)'
    message: "Public APIs must have documentation"
    severity: warning

  security_sensitive_logging:
    name: "Security Sensitive Logging"
    regex: '(?i)(token|password|secret|key|auth|credential)'
    message: "Ensure sensitive data is properly masked in logs"
    severity: warning

  no_enum_alignment:
    name: "No Enum Case Alignment"
    regex: 'case\s+\w+\s{2,}=\s+"'
    message: "Remove extra whitespace alignment in enum cases - use single space around ="
    severity: warning

# Reporter type
reporter: "xcode"

# Strict mode for CI/CD
strict: false

# Warnings as errors (for CI/CD)
# warnings_as_errors: true 